export const country = {
  hot: [
    { id: 40, cnName: '中国', enName: 'China', isOk: true },
    { id: 193, cnName: '美国', enName: 'USA', isOk: true },
    { id: 152, cnName: '俄罗斯', enName: 'Russia', isOk: true },
    { id: 95, cnName: '日本', enName: 'Japan', isOk: true },
    { id: 71, cnName: '德国', enName: 'Germany', isOk: true }
  ],
  allCity: {
    AA: [
      { id: 40, cnName: '中国', enName: 'China', isOk: false },
      { id: 193, cnName: '美国', enName: 'USA', isOk: false },
      { id: 152, cnName: '俄罗斯', enName: 'Russia', isOk: false },
      { id: 95, cnName: '日本', enName: 'Japan', isOk: false },
      { id: 71, cnName: '德国', enName: 'Germany', isOk: false },
      { id: 192, cnName: '英国', enName: 'Great Britain', isOk: false },
      { id: 28, cnName: '巴西', enName: 'Brazil', isOk: false },
      { id: 100, cnName: '韩国', enName: 'South Korea', isOk: false },
      { id: 66, cnName: '法国', enName: 'France', isOk: false },
      { id: 99, cnName: '朝鲜', enName: 'Korea', isOk: false },
      { id: 51, cnName: '捷克', enName: 'Czech Republic', isOk: false },
      { id: 52, cnName: '丹麦', enName: 'Denmark', isOk: false },
      { id: 176, cnName: '瑞士', enName: 'Switzerland', isOk: false }
    ],
    C: [{ id: 40, cnName: '中国', enName: 'China', isOk: false }],
    F: [
      { id: 411, cnName: '中国1', enName: 'China', isOk: false },
      { id: 1931, cnName: '美国1', enName: 'USA', isOk: false },
      { id: 1521, cnName: '俄罗斯1', enName: 'Russia', isOk: false },
      { id: 951, cnName: '日本1', enName: 'Japan', isOk: false },
      { id: 711, cnName: '德国1', enName: 'Germany', isOk: false },
      { id: 1921, cnName: '英国1', enName: 'Great Britain', isOk: false },
      { id: 281, cnName: '巴西1', enName: 'Brazil', isOk: false },
      { id: 1001, cnName: '韩国1', enName: 'South Korea', isOk: false },
      { id: 661, cnName: '法国1', enName: 'France', isOk: false },
      { id: 991, cnName: '朝鲜1', enName: 'Korea', isOk: false },
      { id: 511, cnName: '捷克1', enName: 'Czech Republic', isOk: false },
      { id: 521, cnName: '丹麦1', enName: 'Denmark', isOk: false },
      { id: 1761, cnName: '瑞士1', enName: 'Switzerland', isOk: false }
    ],
    U: [{ id: 401, cnName: '中国1', enName: 'China', isOk: false }],
    P: [
      { id: 412, cnName: '中国2', enName: 'China', isOk: false },
      { id: 1932, cnName: '美国2', enName: 'USA', isOk: false },
      { id: 1522, cnName: '俄罗斯2', enName: 'Russia', isOk: false },
      { id: 952, cnName: '日本2', enName: 'Japan', isOk: false },
      { id: 712, cnName: '德国2', enName: 'Germany', isOk: false },
      { id: 1922, cnName: '英国2', enName: 'Great Britain', isOk: false },
      { id: 282, cnName: '巴西2', enName: 'Brazil', isOk: false },
      { id: 1002, cnName: '韩国2', enName: 'South Korea', isOk: false },
      { id: 662, cnName: '法国2', enName: 'France', isOk: false },
      { id: 992, cnName: '朝鲜2', enName: 'Korea', isOk: false },
      { id: 512, cnName: '捷克2', enName: 'Czech Republic', isOk: false },
      { id: 522, cnName: '丹麦2', enName: 'Denmark', isOk: false },
      { id: 1762, cnName: '瑞士2', enName: 'Switzerland', isOk: false }
    ],
    Q: [{ id: 402, cnName: '中国2', enName: 'China', isOk: false }],
    E: [
      { id: 413, cnName: '中国3', enName: 'China', isOk: false },
      { id: 1933, cnName: '美国3', enName: 'USA', isOk: false },
      { id: 1523, cnName: '俄罗斯3', enName: 'Russia', isOk: false },
      { id: 953, cnName: '日本3', enName: 'Japan', isOk: false },
      { id: 713, cnName: '德国3', enName: 'Germany', isOk: false },
      { id: 1923, cnName: '英国3', enName: 'Great Britain', isOk: false },
      { id: 283, cnName: '巴西3', enName: 'Brazil', isOk: false },
      { id: 1003, cnName: '韩国3', enName: 'South Korea', isOk: false },
      { id: 663, cnName: '法国3', enName: 'France', isOk: false },
      { id: 993, cnName: '朝鲜3', enName: 'Korea', isOk: false },
      { id: 513, cnName: '捷克3', enName: 'Czech Republic', isOk: false },
      { id: 523, cnName: '丹麦3', enName: 'Denmark', isOk: false },
      { id: 1763, cnName: '瑞士3', enName: 'Switzerland', isOk: false }
    ],
    R: [{ id: 403, cnName: '中国3', enName: 'China', isOk: false }],
    M: [
      { id: 414, cnName: '中国4', enName: 'China', isOk: false },
      { id: 1934, cnName: '美国4', enName: 'USA', isOk: false },
      { id: 1524, cnName: '俄罗斯4', enName: 'Russia', isOk: false },
      { id: 954, cnName: '日本4', enName: 'Japan', isOk: false },
      { id: 714, cnName: '德国4', enName: 'Germany', isOk: false },
      { id: 1924, cnName: '英国4', enName: 'Great Britain', isOk: false },
      { id: 284, cnName: '巴西4', enName: 'Brazil', isOk: false },
      { id: 1004, cnName: '韩国4', enName: 'South Korea', isOk: false },
      { id: 664, cnName: '法国4', enName: 'France', isOk: false },
      { id: 994, cnName: '朝鲜4', enName: 'Korea', isOk: false },
      { id: 514, cnName: '捷克4', enName: 'Czech Republic', isOk: false },
      { id: 524, cnName: '丹麦4', enName: 'Denmark', isOk: false },
      { id: 1764, cnName: '瑞士4', enName: 'Switzerland', isOk: false }
    ],
    V: [{ id: 404, cnName: '中国4', enName: 'China', isOk: false }],
    M1: [
      { id: 414, cnName: '中国4', enName: 'China', isOk: false },
      { id: 1934, cnName: '美国4', enName: 'USA', isOk: false },
      { id: 1524, cnName: '俄罗斯4', enName: 'Russia', isOk: false },
      { id: 954, cnName: '日本4', enName: 'Japan', isOk: false },
      { id: 714, cnName: '德国4', enName: 'Germany', isOk: false },
      { id: 1924, cnName: '英国4', enName: 'Great Britain', isOk: false },
      { id: 284, cnName: '巴西4', enName: 'Brazil', isOk: false },
      { id: 1004, cnName: '韩国4', enName: 'South Korea', isOk: false },
      { id: 664, cnName: '法国4', enName: 'France', isOk: false },
      { id: 994, cnName: '朝鲜4', enName: 'Korea', isOk: false },
      { id: 514, cnName: '捷克4', enName: 'Czech Republic', isOk: false },
      { id: 524, cnName: '丹麦4', enName: 'Denmark', isOk: false },
      { id: 1764, cnName: '瑞士4', enName: 'Switzerland', isOk: false }
    ],
    V2: [{ id: 404, cnName: '中国4', enName: 'China', isOk: false }],
    V3: [{ id: 404, cnName: '中国4', enName: 'China', isOk: false }],
    M13: [
      { id: 414, cnName: '中国4', enName: 'China', isOk: false },
      { id: 1934, cnName: '美国4', enName: 'USA', isOk: false },
      { id: 1524, cnName: '俄罗斯4', enName: 'Russia', isOk: false },
      { id: 954, cnName: '日本4', enName: 'Japan', isOk: false },
      { id: 714, cnName: '德国4', enName: 'Germany', isOk: false },
      { id: 1924, cnName: '英国4', enName: 'Great Britain', isOk: false },
      { id: 284, cnName: '巴西100', enName: 'Brazil100', isOk: false },
      { id: 1004, cnName: '韩国4', enName: 'South Korea', isOk: false },
      { id: 664, cnName: '法国4', enName: 'France', isOk: false },
      { id: 994, cnName: '朝鲜4', enName: 'Korea', isOk: false },
      { id: 514, cnName: '捷克4', enName: 'Czech Republic', isOk: false },
      { id: 524, cnName: '丹麦4', enName: 'Denmark', isOk: false },
      { id: 1764, cnName: '瑞士4', enName: 'Switzerland', isOk: false }
    ],
    V23: [{ id: 404, cnName: '中国4', enName: 'China', isOk: false }],
    
  }
}
